# -r means that the bind can repeat without entering prefix again
# -n means that the bind doesn't use the prefix

# Reload config
bind r source-file ~/.tmux.conf

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
